### ISSUE TITLE
Enable full disk encryption

### ISSUE THREAD

**Issue by bneijt** [BigDataRepublic/hyperion#1]

**Comment by DJLemkes** [comment]
Solved in [this](https://github.com/BigDataRepublic/hyperion/commit/39a999926bdf124ae8c4e6b487e109d968470dc3) commit with the `--encrypted` [flag](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/installation_guide/s1-kickstart2-options).
