### ISSUE TITLE
Move home folder to spinning disk, use SSD for scratch/data jobs

### ISSUE THREAD

**Issue by bneijt** [BigDataRepublic/hyperion#2]
- Update centos installation script
- Set up provisioning of a user-owned directory on the SSD and a symlink from their spinning disk home to their SSD folder.
- Make /home partition on HDD, make /var partition on HDD. /var is 500GB, rest is /home

**Comment by DJLemkes** [comment]
Solved in [this](https://github.com/BigDataRepublic/hyperion/commit/39a999926bdf124ae8c4e6b487e109d968470dc3) commit.
