### ISSUE TITLE
Install and configure apcupsd

### ISSUE THREAD

**Issue by StevenReitsma** [BigDataRepublic/hyperion#28]
- [x] Basic installation
- [x] Parameter tuning
- [ ] Check if all k8s pods are shut down gracefully
- [ ] Slack integration/notifications

**Comment by bneijt** [comment]
Live on box and on https://github.com/BigDataRepublic/hyperion/tree/apcupsd
Still needs parameter tuning and slack integration.

**Comment by StevenReitsma** [comment]
Also need to check if k8s pods get shut down gracefully upon shutdown or if we need to do something custom for that

**Comment by DJLemkes** [comment]
Does the work from #33 add any progress to this issue? @bneijt

**Comment by bneijt** [comment]
Decided to merge the current config and push slack integration to a separate issue.
